# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 smartindent nu
---
name: rebuild map
on:
  pull_request:
  push:
  schedule:
    - cron: "20 5 * * 5"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check changed files
        uses: tj-actions/verify-changed-files@v11.1
        id: verify-changed-files
        with:
          files: |
             fqcn-fixer.py
      - name: Set up Python 3.9
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install pyyaml
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: rebuild fqcn map
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          ./fqcn-fixer.py -f example.yml -u
